config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "posts#index"
  root "users#index"
  resources :users
  get "/login", to: "users#index"
  post "/login", to: "users#login"
  get "/signup", to: "users#new"
  get "/logout", to: "users#logout"
  get "/courses/:id/join", to: "courses#join", as: :join_course
  get "/courses/:id/leave", to: "courses#leave", as: :leave_course
  get "/courses/:id/new_student", to: "roles#new"
  get "/courses/:id/remove_student", to: "roles#remove_student"

  resources :courses do
    resources :posts do
      resources :comments, only: [:edit, :show, :create, :update, :destroy, :new]
    end
  end

  # resources :users do
  #   get '/page/:page', action: :index, on: :collection
  # end

  post "/courses/:course_id/posts/new", to: "posts#create"
  post "/courses/:course_id/posts/:post_id/comments/new", to: "comments#create"
  post "/courses/:id/new_student", to: "roles#create", as: :new_student_course


end

app/models/user.rb
class User < ApplicationRecord
    paginates_per 15
    has_many :roles, autosave: true, dependent: :destroy
    has_many :courses, through: :roles
    has_many :posts, dependent: :destroy, as: :postable
    has_many :comments, dependent: :destroy, as: :commentable

    #validations for user name and email
    validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
    validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: URI::MailTo::EMAIL_REGEXP }
    before_save { self.email = email.downcase }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

      def index 
        if session[:current_user] && User.find_by(id: session[:current_user]).present?
            redirect_to controller: 'users', action: 'show', id: session[:current_user]
        else
          session[:current_user] = nil
        end
      end
      
      def show
        @user = User.find(params[:id])
        @courses = @user.courses.order(:name).page params[:courses_pagina]
      end

      def login
        @user = User.find_by(name: params[:name])
        if @user
            session[:current_user] = @user.id
            redirect_to controller: 'users', action: 'show', id: @user.id 
        else
            message = "Something went wrong! Username or email incorrect!"
            redirect_to login_path, alert: message
        end
      end

      def new
        @user = User.new
      end

      def create
        @user = User.new(user_params)
    
        if @user.save
          session[:current_user] = @user.id
          redirect_to controller: 'users', action: 'show', id: @user.id
        else
          render :new, status: :unprocessable_entity
        end
      end
      
      def edit
        @user = User.find(params[:id])
      end
    
      def update
        @user = User.find(params[:id])
    
        if @user.update(user_params)
          session[:current_user] = @user.id
          redirect_to controller: 'users', action: 'show', id: @user.id
        else
          render :new, status: :unprocessable_entity
        end
      end
    
      def destroy
        User.destroy(params[:id])
        redirect_to root_path, status: :see_other
      end

      def logout
        session[:current_user] = nil
        redirect_to root_path
      end
    
      private
      def user_params
        params.require(:user).permit(:name, :email)
      end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<nav class="navbar navbar-default">
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#"><%= @user.name %>'s Conclave</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><li><%= link_to "Home", user_path(@user) %></li></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Edit User", edit_user_path(@user) %></li>
      <li><%= link_to "Delete User", user_path(@user), data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
        } %> 
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

<div class='container'>
  <h1> Edit User Info </h1>
  <%= form_with model: @user do |form| %>
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
      <% @user.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :email %><br>
      <%= form.text_field :email %><br>
      <% @user.errors.full_messages_for(:email).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<body class='login-body'>
  <div class='loginbox'>
    <h1> User Login </h1>

    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    
    <%= form_with model: @user, url: '/login', method: :post, local: true do |form| %>
        <div>
          <%= form.label :name %><br>
          <%= form.text_field :name %>
        </div>
      
        <div>
          <%= form.label :email %><br>
          <%= form.text_field :email %><br>
        </div>
      
        <div>
          <%= form.submit "Log in" %>
          <%= link_to "Sign up", signup_path(@user) %>
  
        </div>
      <% end %>
  </div>
</body>

app/views/users/new.html.erb
<body class='login-body'>
<div class='loginbox'>
  <h1>Sign-up</h1>

  <%= form_with model: @user do |form| %>
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
      <% @user.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :email %><br>
      <%= form.text_field :email %><br>
      <% @user.errors.full_messages_for(:email).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
</div>
</body>

app/views/users/show.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= @user.name %>'s Conclave</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", user_path(@user) %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Create course", new_course_path %> </li>
        <li><%= link_to "Find courses", courses_path %> </li>
        <li><%= link_to "Edit User", edit_user_path(@user) %></li>
        <li><%= link_to "Delete User", user_path(@user), data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
        } %>
        </li>
        <li><%= link_to "Logout", logout_path%> </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class='main container' style='text-align:left;'>
  <div class='container'>
    <h3> My Classes </h3>
  </div>

  <div class='list-group' >
    <% if @courses.length() > 0 %>
      <ul>
        <% @courses.each do |course| %>
          <button style="display:flex;" type="button" class="list-group-item list-group-item-action" aria-current="true">
            <%= link_to course.name, course %>
          </button>
        <% end %>
        <%= paginate @courses, param_name: :courses_pagina %>
      </ul>
    <% else %>
      <div class='container'>
        <p> Looks like you haven't registered for any courses! Please click <%= link_to "here", courses_path %> to find a course to join. </p>
      </div>
    <% end %>
  </div>


  <!--
  TODO: When classes and posts are fixed will create a display for it
    -->

</div>