config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "posts#index"
  root "users#index"
  resources :users
  get "/login", to: "users#index"
  post "/login", to: "users#login"
  get "/signup", to: "users#new"
  get "/logout", to: "users#logout"
  get "/courses/:id/join", to: "courses#join", as: :join_course
  get "/courses/:id/leave", to: "courses#leave", as: :leave_course
  get "/courses/:id/new_student", to: "roles#new"
  get "/courses/:id/remove_student", to: "roles#remove_student"

  resources :courses do
    resources :posts do
      resources :comments, only: [:edit, :show, :create, :update, :destroy, :new]
    end
  end

  # resources :users do
  #   get '/page/:page', action: :index, on: :collection
  # end

  post "/courses/:course_id/posts/new", to: "posts#create"
  post "/courses/:course_id/posts/:post_id/comments/new", to: "comments#create"
  post "/courses/:id/new_student", to: "roles#create", as: :new_student_course


end

app/controllers/courses_controller.rb
class CoursesController < AuthenticatedController
    before_action :check_id
    before_action :set_course, only: %i[ show edit update destroy join leave]
  
    # GET /posts or /posts.json
    def index
      @courses = Course.order(:name).page params[:page]
      #Temporary variable for the navbar, until we find a better solution
      @user = @current_user
    end
  
    def show
      @roles = Role.where(course_id: @course.id).order(:user_id).page params[:mem_pagina]
      #Temporary variable for the navbar, until we find a better solution
      @user = @current_user

      @role = Role.where(user_id: @user, course_id:@course.id).first
      @posts = Post.where(course_id: @course.id).order(:created_at).page params[:posts_pagina]

      user_ids = []
      @posts.each do |post|
        user_ids << post.user_id
      end
      posts_users = User.where(id: user_ids)
      @posts_users_hash = Hash[posts_users.collect { |v| [v.id, v]}]


    end
  
    def new
      @course = Course.new
      @user = @current_user
    end
  
    def edit
      #Temporary variable for the navbar, until we find a better solution
      @user = @current_user

    end

    def leave
      current_role = @course.roles.find_by(user_id: @current_user.id)
      if current_role.role == 1 or current_role.role == 2
        @course.roles.find_by(user_id: @current_user.id).destroy
      end
        redirect_to @current_user
    end
  
    def create
      @user = @current_user
      @course = Course.new(course_params)
      @course.roles.build(user: @current_user, course: @course, role:0)
      # @course.users << User.find(@current_user.id)

  
      respond_to do |format|
        if @course.save
          format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
          format.json { render :show, status: :created, location: @course }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @course.errors, status: :unprocessable_entity }
        end
      end
    end

    def join
      @course.roles.create(user: @current_user, course: @course, role: 1)
      redirect_to course_url(@course)
    end
  
    def update
      respond_to do |format|
        if @course.update(course_params)
          format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
          format.json { render :show, status: :ok, location: @course }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @course.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def destroy
      roles = Role.where(course_id: @course.id)
      roles.each do |role|
        role.destroy
      end
      
      posts = Post.where(course_id: @course.id)
      posts.each do |post|
        post.destroy
      end
      
      @course.destroy
      redirect_to courses_path, notice: "Course was successfully destroyed", status: :see_other

    end
  
    private
  
      def check_id
        return render_not_found unless (!params[:id] or Course.find_by(id: params[:id]))
      end
    
    # Use callbacks to share common setup or constraints between actions.
      def set_course
        @course = Course.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def course_params
        params.require(:course).permit(:name)
      end
  end
  

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_area :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= @user.name %>'s Conclave</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><li><%= link_to "Home", user_path(@user) %></li></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Create course", new_course_path %> </li>
        <li><%= link_to "Edit User", edit_user_path(@user) %></li>
        <li><%= link_to "Delete User", user_path(@user), data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
          } %> 
        </li>
        <li><%= link_to "Logout", logout_path%> </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<h1>Editing course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Show this course", @course %> |
  <%= link_to "Back to courses", course_path %>
</div>

app/views/courses/index.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= @user.name %>'s Conclave</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><li><%= link_to "Home", user_path(@user) %></li></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Create course", new_course_path %> </li>
        <li><%= link_to "Edit User", edit_user_path(@user) %></li>
        <li><%= link_to "Delete User", user_path(@user), data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
          } %> 
        </li>
        <li><%= link_to "Logout", logout_path%> </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<p style="color: green"><%= notice %></p>

<div class='container-2'>
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">Courses</div>
    <!-- Table -->
    <table class="table">
      <tr>
        <th>Course Name</th>
        <th>Instructor</th>
        <th>Access</th>
      </tr>
      <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td></td>
        <td>
        <% if @current_user.courses.include?(course)%>
        <%= link_to "View course", course %>
        <%else%>
        <%=link_to "Join course", join_course_path(course) %>
        <%end%>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
  <%= paginate @courses %>
</div>

app/views/courses/new.html.erb
<nav class="navbar navbar-default">
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#"><%= @user.name %>'s Conclave</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><%= link_to "Home", user_path(@user) %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Logout", logout_path%> </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>
<div class='container'>
<h1>New course</h1>

<%= render "form", course: @course %>

<br>

<button class="btn btn-primary"><%= link_to "Back to courses", courses_path %></button>

</div>

app/views/courses/show.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= @user.name %>'s Conclave</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><li><%= link_to "Home", user_path(@user) %></li></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Create post", new_course_post_path(@course) %> </li>
      <% if is_instructor? @role.role %> 
        <li class="nav-link"><%= link_to "Edit Course", edit_course_path(@course) %></li>
        <li class="nav-link"><%= link_to "Delete Course", course_path(@course), data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
          } %>
          </li>
        <% end %>
        <li><%= link_to "Logout", logout_path%> </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class='main container' style='text-align:left;'>
  <h3><%=@course.name %></h3>
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">Posts</div>
    <% if @posts.length() < 1%>
      <div class='container'>
        <h5>No posts yet :/ Make one <%= link_to "here!", new_course_post_path(@course) %> </h5>
      </div>
    <% else %>
      <!-- Table -->
      <table class="table">
        <tr>
          <th>Author</th>
          <th>Title</th>
          <th>Body</th>
          <th></th>
        </tr>
        <% @posts.each do |post|%>
          <tr>
            <td><%=  @posts_users_hash[post.user_id].name %></td>
            <td><%= link_to post.title, course_post_path(@course,post) %></td>
            <td><%= post.body %></td>
            <td>
              <div class='button-div'>
                <button class='btn btn-primary'><%= link_to "Edit", edit_course_post_path(@course,post) %></button>
                <button class='btn btn-primary'><%= link_to "Delete", course_post_path(@course,post.id), data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %></button>
              </div>
            </td>
          </tr>
        <% end %>
      </table>
    <% end %>
  </div>
  <%= paginate @posts, param_name: :posts_pagina %>

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Members</div>
  <!-- Table -->
  <table class="table">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Role</th>
      <th></th>
<!--      <th>Leave Course</th>-->
    </tr>
    <% @roles.each do |role|%>
    <tr>
      <td><%= link_to role.user.name, role.user%></td>
      <td><%= role.user.email%></td>
      <td><%= role_to_text role.role %></td>
      <td>
      <%# if role.role == 0%>
        <%#= "Cannot leave course as instructor"%>
      <%#end%>
      <% if @role.role == 0 and (role.role == 1 or role.role == 2) %>
        <%= link_to "Remove", {:controller => "roles", action: :remove_student, user_id: role.user}%>
      <%end%>
      </td>
    </tr>
    <% end %>
  </table>
</div>
<%= paginate @roles, param_name: :mem_pagina %>

  <div>
    <% if @role.role ==0 %>
      <%= link_to "Add a student", new_student_course_path%>
    <% else %>
      <%= link_to "Leave Course", leave_course_path(@role.course)%>
    <% end %>
  </div>
  <br/>
</div>