config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "posts#index"
  root "users#index"
  resources :users
  get "/login", to: "users#index"
  post "/login", to: "users#login"
  get "/signup", to: "users#new"
  get "/logout", to: "users#logout"
  get "/courses/:id/join", to: "courses#join", as: :join_course
  get "/courses/:id/leave", to: "courses#leave", as: :leave_course
  get "/courses/:id/new_student", to: "roles#new"
  get "/courses/:id/remove_student", to: "roles#remove_student"

  resources :courses do
    resources :posts do
      resources :comments, only: [:edit, :show, :create, :update, :destroy, :new]
    end
  end

  # resources :users do
  #   get '/page/:page', action: :index, on: :collection
  # end

  post "/courses/:course_id/posts/new", to: "posts#create"
  post "/courses/:course_id/posts/:post_id/comments/new", to: "comments#create"
  post "/courses/:id/new_student", to: "roles#create", as: :new_student_course


end

app/models/post.rb
class Post < ApplicationRecord
  # belongs_to :user
  # belongs_to :class
  paginates_per 15
  belongs_to :postable, polymorphic: true, optional: true
  has_many :comments, dependent: :destroy, as: :commentable

  # validates_presence_of :user
  # validates_presence_of :class

  # validations for post title and body
  validates :title, presence: true, length: { minimum: 3, maximum: 15 }
  validates :body, presence: true, length: { minimum: 8, maximum: 100 }
end

app/controllers/posts_controller.rb
class PostsController < AuthenticatedController
  before_action :check_id
  before_action :set_post, only: %i[ show edit update destroy ]



  def index
    @posts = Post.order(:title).page params[:page]
  end

  def show
    @comments = Comment.where(post_id: @post.id).order(:created_at).page params[:comments_pagina]
    user_ids = []
    @comments.each do |comment|
      user_ids << comment.user_id
    end
    comments_users = User.where(id: user_ids)
    @comments_users_hash = Hash[comments_users.collect { |v| [v.id, v]}]

    @post_user = User.find(@post.user_id)
  end

  def new
    @post = Post.new
    @user = @current_user
    @course = Course.find(params[:course_id])

  end

  def create
    @user = @current_user
    course_id = params[:course_id]
    @course = Course.find(course_id)
    @post = Post.new(user_id: @current_user.id, course_id: course_id,
                     title: post_params[:title], body: post_params[:body])


    if @post.save
      redirect_to controller: 'posts', action: 'show', id: @post.id, course_id: course_id
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    unless helpers.is_instructor?(@role.role) or (@post.user_id == @current_user.id)
      render_not_found
    end
  end

  def update

    if helpers.is_instructor?(@role.role) or (@post.user_id == @current_user.id)
      if @post.update(post_params)
        redirect_to controller: 'courses', action: 'show', id: @post.course_id
      else
        render :edit, status: :unprocessable_entity
      end
    else
      redirect_to course_post_path @post
    end

  end

  def destroy
    if helpers.is_instructor?(@role.role) or (@post.user_id == @current_user.id)
      @post = Post.find(params[:id])
      Comment.where(post_id: @post.id).delete_all
      @post.destroy
      redirect_to course_path(@course), status: :see_other
    end
  end

  private
  def post_params
    params.require(:post).permit(:course_id, :title, :body)
  end

  def set_post
    @user = @current_user
    @post = Post.find(params[:id])
    @course = Course.find(@post.course_id)
    @role = Role.where(course_id: @course, user_id: @current_user).first
  end

  def check_id
    render_not_found unless (!params[:id] or Post.find_by(id: params[:id]))
  end



end

app/views/posts/_form.html.erb
<%= form_with model: post, url: url do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @post.errors.full_messages_for(:title).each do |message| %>
          <div class="error_msg"><%= message %></div><br>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
    <% @post.errors.full_messages_for(:body).each do |message| %>
          <div class="error_msg"><%= message %></div><br>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<nav class="navbar navbar-default">
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#"><%= @user.name %>'s Conclave</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><%= link_to "Home", user_path(@user) %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <li><%= link_to @course.name, course_path(@course) %> </li>
        <li><%= link_to "Create new post", new_course_post_path(@course) %> </li>
        <% if is_instructor? @user_role or @user.id == @post.user_id%> 

        <li class="nav-link"><%= link_to "Delete Post", course_post_path(@course), data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
        } %> 
        </li>
        <% end %>
        <li><%= link_to "Logout", logout_path%> </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>
<div class='container'>
    <h1>Edit Post</h1>

    <%= render "form", post:@post, url: course_post_path(@post) %>

</div>

app/views/posts/new.html.erb
<nav class="navbar navbar-default">
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#"><%= @user.name %>'s Conclave</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><%= link_to "Home", user_path(@user) %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <li><%= link_to @course.name, course_path(@course) %> </li>
        <li><%= link_to "Logout", logout_path%> </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>
<div class='container'>
    <h1>Create post</h1>

    <%= render "form", post: @post, url: request.original_url %>
</div>

app/views/posts/show.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= @user.name %>'s Conclave</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><li><%= link_to "Home", user_path(@user) %></li></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Back to Course", course_path(@course) %> </li>
        <li><%= link_to "Create new post", new_course_post_path(@course) %> </li>
        <% if is_instructor? @user_role or @user.id == @post.user_id%>
          <li class="nav-link"><%= link_to "Edit Post", edit_course_post_path(@course) %></li>
          <li class="nav-link"><%= link_to "Delete Post", course_post_path(@course), data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
          } %>
          </li>
        <% end %>
        <li><%= link_to "Logout", logout_path%> </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid">
  <div>
    <h3><%= @post.title %></h3>
  </div>
  <div class='container-fluid'>
    <div>
      <h6><%= User.find(@post.user_id).name %></h6>
    </div>
    <p><%= @post.body %></p>
    <hr/>
    <ol class="list-group list-group-numbered">
      <% @comments.each do |comment|%>
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1"><%= @comments_users_hash[comment.user_id].name %></h5>
            </div>
            <p class="mb-1"><%= comment.body %></p>
            <% if is_instructor? @role.role or @user.id == comment.user_id%>
              <small>
                <%= link_to "Edit", edit_course_post_comment_path(@course,@post,comment) %>
                <%= link_to "Delete", course_post_comment_path(@course,@post,comment), data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
              </small>
            <% end %>
          </div>
        </li>
      <% end %>
    </ol>
    <%= paginate @comments, param_name: :comments_pagina %>
  </div>
</div>
<div class='container'>
  <button class='btn btn-primary'><%= link_to "New Comment", new_course_post_comment_path(course_id: @course.id, post_id: @post.id)%></a>
  </button>
</div>